services:
  gaming-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '0.0.0.0:3000:3000'
    restart: unless-stopped

  gaming-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - gaming-server
    restart: unless-stopped
