export const TERRITORIES = {
  // --- NORTH (Top) ---
  scotland: {
    name: 'Scotland',
    capital: 'Glasgow',
    colorKey: '#cccc33',
    cx: 230,
    cy: 50,
    neighbors: ['england', 'norway', 'ireland'],
  },
  ireland: {
    name: 'Ireland',
    capital: 'Dublin',
    colorKey: '#05ff23',
    cx: 160,
    cy: 100,
    neighbors: ['england', 'scotland'],
  },
  england: {
    name: 'England',
    capital: 'London',
    colorKey: '#ff4005',
    cx: 240,
    cy: 160,
    neighbors: ['scotland', 'ireland', 'batavia', 'portugal'],
  },
  norway: {
    name: 'Norway',
    capital: 'Oslo',
    colorKey: '#ff9905',
    cx: 380,
    cy: 20,
    neighbors: ['sweden', 'denmark', 'scotland'],
  },
  sweden: {
    name: 'Sweden',
    capital: 'Stockholm',
    colorKey: '#4a66f7',
    cx: 470,
    cy: 30,
    neighbors: ['norway', 'denmark', 'baltic_states'],
  },
  denmark: {
    name: 'Denmark',
    capital: 'Copenhagen',
    colorKey: '#ff5d05',
    cx: 390,
    cy: 110,
    neighbors: ['sweden', 'norway', 'hanover'],
  },

  // --- WEST (France and Iberia) ---
  france: {
    name: 'France',
    capital: 'Paris',
    colorKey: '#010ce1',
    cx: 250,
    cy: 220,
    neighbors: ['belgium', 'rhine_west', 'helvetia', 'piemonte', 'catalonia'],
  },
  catalonia: {
    name: 'Catalonia',
    capital: 'Barcelona',
    colorKey: '#f4a398',
    cx: 230,
    cy: 355,
    neighbors: ['france', 'spain'],
  },
  spain: {
    name: 'Spain',
    capital: 'Madrid',
    colorKey: '#2841fe',
    cx: 130,
    cy: 365,
    neighbors: ['catalonia', 'portugal', 'barbary'],
  },
  portugal: {
    name: 'Portugal',
    capital: 'Lisbon',
    colorKey: '#64fa00',
    cx: 40,
    cy: 365,
    neighbors: ['spain', 'england'],
  },

  // --- CENTER (Germany and Benelux) ---
  batavia: {
    name: 'Low Countries',
    capital: 'Amsterdam',
    colorKey: '#5bf9a5',
    cx: 310,
    cy: 150,
    neighbors: ['belgium', 'hanover', 'england'],
  },
  belgium: {
    name: 'Belgium',
    capital: 'Waterloo',
    colorKey: '#ef6394',
    cx: 305,
    cy: 185,
    neighbors: ['france', 'batavia', 'rhine_west'],
  },
  hanover: {
    name: 'Hanover',
    capital: 'Hanover',
    colorKey: '#eec400',
    cx: 370,
    cy: 160,
    neighbors: ['batavia', 'denmark', 'brandenburg', 'saxony', 'rhine_west'],
  },
  rhine_west: {
    name: 'Rhineland',
    capital: 'Cologne',
    colorKey: '#9f4dfb',
    cx: 345,
    cy: 190,
    neighbors: ['france', 'belgium', 'hanover', 'saxony', 'bavaria'],
  },
  saxony: {
    name: 'Saxony',
    capital: 'Dresden',
    colorKey: '#f5e2d1',
    cx: 400,
    cy: 180,
    neighbors: ['rhine_west', 'hanover', 'brandenburg', 'bohemia', 'bavaria'],
  },
  bavaria: {
    name: 'Bavaria',
    capital: 'Munich',
    colorKey: '#98e8f4',
    cx: 380,
    cy: 230,
    neighbors: ['rhine_west', 'saxony', 'austria', 'helvetia'],
  },
  helvetia: {
    name: 'Switzerland',
    capital: 'Geneva',
    colorKey: '#01e1d4',
    cx: 330,
    cy: 265,
    neighbors: ['france', 'bavaria', 'piemonte'],
  },

  // --- EAST (Prussia, Austria, Russia) ---
  brandenburg: {
    name: 'Prussia',
    capital: 'Berlin',
    colorKey: '#c6f4c6',
    cx: 420,
    cy: 150,
    neighbors: ['hanover', 'saxony', 'bohemia', 'east_prussia', 'poland'],
  },
  east_prussia: {
    name: 'East Prussia',
    capital: 'Königsberg',
    colorKey: '#b23904',
    cx: 490,
    cy: 120,
    neighbors: ['brandenburg', 'poland', 'baltic_states'],
  },
  bohemia: {
    name: 'Bohemia',
    capital: 'Prague',
    colorKey: '#dcfb4d',
    cx: 440,
    cy: 200,
    neighbors: ['saxony', 'brandenburg', 'austria', 'poland'],
  },
  austria: {
    name: 'Austria',
    capital: 'Vienna',
    colorKey: '#e000fa',
    cx: 435,
    cy: 245,
    neighbors: ['bavaria', 'bohemia', 'hungary', 'venetia', 'dalmatia'],
  },
  poland: {
    name: 'Poland',
    capital: 'Warsaw',
    colorKey: '#05a599',
    cx: 495,
    cy: 195,
    neighbors: ['brandenburg', 'east_prussia', 'galicia', 'belarus', 'bohemia'],
  },
  galicia: {
    name: 'Galicia',
    capital: 'Lviv',
    colorKey: '#994133',
    cx: 550,
    cy: 210,
    neighbors: ['poland', 'hungary', 'ukraine'],
  },
  hungary: {
    name: 'Hungary',
    capital: 'Budapest',
    colorKey: '#949439',
    cx: 500,
    cy: 250,
    neighbors: ['austria', 'galicia', 'serbia', 'wallachia', 'dalmatia'],
  },
  dalmatia: {
    name: 'Illyrian Province',
    capital: 'Ljubljana',
    colorKey: '#35fd43',
    cx: 430,
    cy: 300,
    neighbors: ['venetia', 'serbia', 'austria', 'hungary'],
  },

  // --- RUSSIAN EMPIRE (Far East) ---
  baltic_states: {
    name: 'Baltic States',
    capital: 'Riga',
    colorKey: '#339910',
    cx: 540,
    cy: 70,
    neighbors: ['sweden', 'east_prussia', 'belarus', 'moscow'],
  },
  belarus: {
    name: 'Belarus',
    capital: 'Smolensk',
    colorKey: '#336610',
    cx: 580,
    cy: 150,
    neighbors: ['poland', 'baltic_states', 'moscow', 'ukraine'],
  },
  moscow: {
    name: 'Moscow',
    capital: 'Moscow',
    colorKey: '#6bce10',
    cx: 720,
    cy: 100,
    neighbors: ['belarus', 'ukraine', 'baltic_states'],
  },
  ukraine: {
    name: 'Ukraine',
    capital: 'Kiev',
    colorKey: '#cee763',
    cx: 690,
    cy: 200,
    neighbors: ['belarus', 'moscow', 'galicia', 'wallachia'],
  },

  // --- SOUTH (Italy) ---
  piemonte: {
    name: 'Piedmont',
    capital: 'Turin',
    colorKey: '#068598',
    cx: 320,
    cy: 300,
    neighbors: ['france', 'helvetia', 'lombardia', 'papal_states', 'venetia'],
  },
  lombardia: {
    name: 'Lombardy',
    capital: 'Milan',
    colorKey: '#cefa00',
    cx: 360,
    cy: 300,
    neighbors: ['piemonte', 'venetia', 'papal_states'],
  },
  venetia: {
    name: 'Venetia',
    capital: 'Venice',
    colorKey: '#b24104',
    cx: 390,
    cy: 290,
    neighbors: ['piemonte', 'austria', 'dalmatia', 'lombardia', 'papal_states'],
  },
  papal_states: {
    name: 'Papal States',
    capital: 'Rome',
    colorKey: '#fece28',
    cx: 385,
    cy: 365,
    neighbors: ['piemonte', 'lombardia', 'venetia', 'naples'],
  },
  naples: {
    name: 'Naples',
    capital: 'Naples',
    colorKey: '#1ad701',
    cx: 415,
    cy: 385,
    neighbors: ['papal_states', 'tunisia'],
  },

  // --- SOUTH (Balkans) ---
  serbia: {
    name: 'Serbia',
    capital: 'Belgrade',
    colorKey: '#ff9400',
    cx: 520,
    cy: 320,
    neighbors: ['dalmatia', 'hungary', 'wallachia', 'bulgaria', 'greece'],
  },
  wallachia: {
    name: 'Wallachia',
    capital: 'Bucharest',
    colorKey: '#7be7e7',
    cx: 570,
    cy: 280,
    neighbors: ['hungary', 'serbia', 'bulgaria', 'ukraine'],
  },
  bulgaria: {
    name: 'Bulgaria',
    capital: 'Sofia',
    colorKey: '#ceade7',
    cx: 570,
    cy: 350,
    neighbors: ['serbia', 'wallachia', 'greece', 'constantinople'],
  },
  greece: {
    name: 'Greece',
    capital: 'Athens',
    colorKey: '#33e7e7',
    cx: 570,
    cy: 435,
    neighbors: ['bulgaria', 'serbia', 'constantinople'],
  },

  // --- MEDITERRANEAN AND AFRICA (Background) ---
  constantinople: {
    name: 'Constantinople',
    capital: 'Konstantiniyye',
    colorKey: '#fd35c2',
    cx: 630,
    cy: 375,
    neighbors: ['bulgaria', 'levant', 'greece'],
  },
  levant: {
    name: 'Levant',
    capital: 'Jerusalem',
    colorKey: '#7e03bd',
    cx: 750,
    cy: 520,
    neighbors: ['constantinople', 'egypt'],
  },
  egypt: {
    name: 'Egypt',
    capital: 'Cairo',
    colorKey: '#d79801',
    cx: 650,
    cy: 570,
    neighbors: ['cyrenaica', 'levant'],
  },
  cyrenaica: {
    name: 'Cyrenaica',
    capital: 'Benghazi',
    colorKey: '#9bf868',
    cx: 495,
    cy: 510,
    neighbors: ['tunisia', 'egypt'],
  },
  tunisia: {
    name: 'Tunisia',
    capital: 'Tunis',
    colorKey: '#b98df5',
    cx: 340,
    cy: 460,
    neighbors: ['barbary', 'naples', 'cyrenaica'],
  },
  barbary: {
    name: 'Barbary',
    capital: 'Algiers',
    colorKey: '#11ffb9',
    cx: 190,
    cy: 460,
    neighbors: ['spain', 'tunisia'],
  },
};
