export const TERRITORIES = {
  // --- NORTH (Top) ---
  scotland: {
    name: 'Scotland',
    capital: 'Glasgow',
    isRegCapital: false,
    colorKey: '#cccc33',
    cx: 345,
    cy: 75,
    neighbors: ['england', 'norway', 'ireland'],
  },
  ireland: {
    name: 'Ireland',
    capital: 'Dublin',
    isRegCapital: false,
    colorKey: '#05ff23',
    cx: 240,
    cy: 142,
    neighbors: ['england', 'scotland'],
  },
  england: {
    name: 'England',
    capital: 'London',
    isRegCapital: true,
    colorKey: '#ff4005',
    cx: 352,
    cy: 200,
    neighbors: ['scotland', 'ireland', 'batavia', 'portugal'],
  },
  norway: {
    name: 'Norway',
    capital: 'Oslo',
    isRegCapital: false,
    colorKey: '#ff9905',
    cx: 570,
    cy: 33,
    neighbors: ['sweden', 'denmark', 'scotland'],
  },
  sweden: {
    name: 'Sweden',
    capital: 'Stockholm',
    isRegCapital: true,
    colorKey: '#4a66f7',
    cx: 705,
    cy: 42,
    neighbors: ['norway', 'denmark', 'baltic_states'],
  },
  denmark: {
    name: 'Denmark',
    capital: 'Copenhagen',
    isRegCapital: false,
    colorKey: '#ff5d05',
    cx: 585,
    cy: 150,
    neighbors: ['sweden', 'norway', 'hanover'],
  },

  // --- WEST (France and Iberia) ---
  france: {
    name: 'France',
    capital: 'Paris',
    isRegCapital: true,
    colorKey: '#010ce1',
    cx: 375,
    cy: 300,
    neighbors: ['belgium', 'rhine_west', 'helvetia', 'piemonte', 'catalonia'],
  },
  catalonia: {
    name: 'Catalonia',
    capital: 'Barcelona',
    isRegCapital: false,
    colorKey: '#f4a398',
    cx: 338,
    cy: 475,
    neighbors: ['france', 'spain'],
  },
  spain: {
    name: 'Spain',
    capital: 'Madrid',
    isRegCapital: true,
    colorKey: '#2841fe',
    cx: 195,
    cy: 492,
    neighbors: ['catalonia', 'portugal', 'barbary'],
  },
  portugal: {
    name: 'Portugal',
    capital: 'Lisbon',
    isRegCapital: false,
    colorKey: '#64fa00',
    cx: 60,
    cy: 500,
    neighbors: ['spain', 'england'],
  },

  // --- CENTER (Germany and Benelux) ---
  batavia: {
    name: 'Batavia',
    capital: 'Amsterdam',
    isRegCapital: true,
    colorKey: '#5bf9a5',
    cx: 465,
    cy: 200,
    neighbors: ['belgium', 'hanover', 'england'],
  },
  belgium: {
    name: 'Belgium',
    capital: 'Waterloo',
    isRegCapital: false,
    colorKey: '#ef6394',
    cx: 458,
    cy: 250,
    neighbors: ['france', 'batavia', 'rhine_west'],
  },
  hanover: {
    name: 'Hanover',
    capital: 'Hanover',
    isRegCapital: false,
    colorKey: '#eec400',
    cx: 540,
    cy: 200,
    neighbors: ['batavia', 'denmark', 'brandenburg', 'saxony', 'rhine_west'],
  },
  rhine_west: {
    name: 'Rhineland',
    capital: 'Cologne',
    isRegCapital: false,
    colorKey: '#9f4dfb',
    cx: 518,
    cy: 250,
    neighbors: ['france', 'belgium', 'hanover', 'saxony', 'bavaria'],
  },
  saxony: {
    name: 'Saxony',
    capital: 'Dresden',
    isRegCapital: false,
    colorKey: '#f5e2d1',
    cx: 600,
    cy: 233,
    neighbors: ['rhine_west', 'hanover', 'brandenburg', 'bohemia', 'bavaria'],
  },
  bavaria: {
    name: 'Bavaria',
    capital: 'Munich',
    isRegCapital: false,
    colorKey: '#98e8f4',
    cx: 570,
    cy: 333,
    neighbors: ['rhine_west', 'saxony', 'austria', 'helvetia'],
  },
  helvetia: {
    name: 'Switzerland',
    capital: 'Geneva',
    isRegCapital: false,
    colorKey: '#01e1d4',
    cx: 495,
    cy: 358,
    neighbors: ['france', 'bavaria', 'piemonte'],
  },

  // --- EAST (Prussia, Austria, Russia) ---
  brandenburg: {
    name: 'Prussia',
    capital: 'Berlin',
    isRegCapital: true,
    colorKey: '#c6f4c6',
    cx: 630,
    cy: 200,
    neighbors: ['hanover', 'saxony', 'bohemia', 'east_prussia', 'poland'],
  },
  east_prussia: {
    name: 'East Prussia',
    capital: 'Königsberg',
    isRegCapital: true,
    colorKey: '#b23904',
    cx: 735,
    cy: 167,
    neighbors: ['brandenburg', 'poland', 'baltic_states'],
  },
  bohemia: {
    name: 'Bohemia',
    capital: 'Prague',
    isRegCapital: false,
    colorKey: '#dcfb4d',
    cx: 660,
    cy: 267,
    neighbors: ['saxony', 'brandenburg', 'austria', 'poland'],
  },
  austria: {
    name: 'Austria',
    capital: 'Vienna',
    isRegCapital: true,
    colorKey: '#e000fa',
    cx: 645,
    cy: 333,
    neighbors: ['bavaria', 'bohemia', 'hungary', 'venetia', 'dalmatia'],
  },
  poland: {
    name: 'Poland',
    capital: 'Warsaw',
    isRegCapital: false,
    colorKey: '#05a599',
    cx: 743,
    cy: 250,
    neighbors: ['brandenburg', 'east_prussia', 'galicia', 'belarus', 'bohemia'],
  },
  galicia: {
    name: 'Galicia',
    capital: 'Lviv',
    isRegCapital: false,
    colorKey: '#994133',
    cx: 825,
    cy: 283,
    neighbors: ['poland', 'hungary', 'ukraine'],
  },
  hungary: {
    name: 'Hungary',
    capital: 'Budapest',
    isRegCapital: false,
    colorKey: '#949439',
    cx: 750,
    cy: 333,
    neighbors: ['austria', 'galicia', 'serbia', 'wallachia', 'dalmatia'],
  },
  dalmatia: {
    name: 'Illyrian Province',
    capital: 'Ljubljana',
    isRegCapital: false,
    colorKey: '#35fd43',
    cx: 645,
    cy: 400,
    neighbors: ['venetia', 'serbia', 'austria', 'hungary'],
  },

  // --- RUSSIAN EMPIRE (Far East) ---
  baltic_states: {
    name: 'Baltic States',
    capital: 'Riga',
    isRegCapital: false,
    colorKey: '#339910',
    cx: 818,
    cy: 100,
    neighbors: ['sweden', 'east_prussia', 'belarus', 'moscow'],
  },
  belarus: {
    name: 'Belarus',
    capital: 'Smolensk',
    isRegCapital: false,
    colorKey: '#336610',
    cx: 848,
    cy: 217,
    neighbors: ['poland', 'baltic_states', 'moscow', 'ukraine'],
  },
  moscow: {
    name: 'Moscow',
    capital: 'Moscow',
    isRegCapital: true,
    colorKey: '#6bce10',
    cx: 1050,
    cy: 133,
    neighbors: ['belarus', 'ukraine', 'baltic_states'],
  },
  ukraine: {
    name: 'Ukraine',
    capital: 'Kiev',
    isRegCapital: false,
    colorKey: '#cee763',
    cx: 1035,
    cy: 267,
    neighbors: ['belarus', 'moscow', 'galicia', 'wallachia'],
  },

  // --- SOUTH (Italy) ---
  piemonte: {
    name: 'Piedmont',
    capital: 'Turin',
    isRegCapital: false,
    colorKey: '#068598',
    cx: 480,
    cy: 408,
    neighbors: ['france', 'helvetia', 'lombardia', 'papal_states', 'venetia'],
  },
  lombardia: {
    name: 'Lombardy',
    capital: 'Milan',
    isRegCapital: true,
    colorKey: '#cefa00',
    cx: 533,
    cy: 400,
    neighbors: ['piemonte', 'venetia', 'papal_states'],
  },
  venetia: {
    name: 'Venetia',
    capital: 'Venice',
    isRegCapital: false,
    colorKey: '#b24104',
    cx: 585,
    cy: 392,
    neighbors: ['piemonte', 'austria', 'dalmatia', 'lombardia', 'papal_states'],
  },
  papal_states: {
    name: 'Papal States',
    capital: 'Rome',
    isRegCapital: true,
    colorKey: '#fece28',
    cx: 570,
    cy: 483,
    neighbors: ['piemonte', 'lombardia', 'venetia', 'naples'],
  },
  naples: {
    name: 'Naples',
    capital: 'Naples',
    isRegCapital: true,
    colorKey: '#1ad701',
    cx: 623,
    cy: 517,
    neighbors: ['papal_states', 'tunisia'],
  },

  // --- SOUTH (Balkans) ---
  serbia: {
    name: 'Serbia',
    capital: 'Belgrade',
    isRegCapital: true,
    colorKey: '#ff9400',
    cx: 765,
    cy: 433,
    neighbors: ['dalmatia', 'hungary', 'wallachia', 'bulgaria', 'greece'],
  },
  wallachia: {
    name: 'Wallachia',
    capital: 'Bucharest',
    isRegCapital: false,
    colorKey: '#7be7e7',
    cx: 855,
    cy: 383,
    neighbors: ['hungary', 'serbia', 'bulgaria', 'ukraine'],
  },
  bulgaria: {
    name: 'Bulgaria',
    capital: 'Sofia',
    isRegCapital: false,
    colorKey: '#ceade7',
    cx: 855,
    cy: 467,
    neighbors: ['serbia', 'wallachia', 'greece', 'constantinople'],
  },
  greece: {
    name: 'Greece',
    capital: 'Athens',
    isRegCapital: false,
    colorKey: '#33e7e7',
    cx: 855,
    cy: 583,
    neighbors: ['bulgaria', 'serbia', 'constantinople'],
  },

  // --- MEDITERRANEAN AND AFRICA (Background) ---
  constantinople: {
    name: 'Constantinople',
    capital: 'Konstantiniyye',
    isRegCapital: true,
    colorKey: '#fd35c2',
    cx: 945,
    cy: 500,
    neighbors: ['bulgaria', 'levant', 'greece'],
  },
  levant: {
    name: 'Levant',
    capital: 'Jerusalem',
    isRegCapital: false,
    colorKey: '#7e03bd',
    cx: 1125,
    cy: 700,
    neighbors: ['constantinople', 'egypt'],
  },
  egypt: {
    name: 'Egypt',
    capital: 'Cairo',
    isRegCapital: true,
    colorKey: '#d79801',
    cx: 975,
    cy: 750,
    neighbors: ['cyrenaica', 'levant'],
  },
  cyrenaica: {
    name: 'Cyrenaica',
    capital: 'Benghazi',
    isRegCapital: false,
    colorKey: '#9bf868',
    cx: 743,
    cy: 683,
    neighbors: ['tunisia', 'egypt'],
  },
  tunisia: {
    name: 'Tunisia',
    capital: 'Tunis',
    isRegCapital: false,
    colorKey: '#b98df5',
    cx: 525,
    cy: 617,
    neighbors: ['barbary', 'naples', 'cyrenaica'],
  },
  barbary: {
    name: 'Barbary',
    capital: 'Algiers',
    isRegCapital: false,
    colorKey: '#11ffb9',
    cx: 285,
    cy: 617,
    neighbors: ['spain', 'tunisia'],
  },
};
