export const TERRITORIES = {
  iceland: { name: "Islandia", cx: 230, cy: 95, neighbors: ["great_britain", "norway"] },
  norway: { name: "Noruega", cx: 390, cy: 85, neighbors: ["iceland", "sweden", "finland", "great_britain"] },
  sweden: { name: "Suecia", cx: 430, cy: 120, neighbors: ["norway", "finland", "denmark"] },
  finland: { name: "Finlandia", cx: 490, cy: 90, neighbors: ["norway", "sweden", "russia_nw"] },
  russia_nw: { name: "Rusia NO", cx: 560, cy: 115, neighbors: ["finland", "estonia", "belarus", "ukraine"] },
  great_britain: { name: "Gran Bretaña", cx: 265, cy: 185, neighbors: ["iceland", "norway", "france", "ireland"] },
  ireland: { name: "Irlanda", cx: 220, cy: 200, neighbors: ["great_britain"] },
  denmark: { name: "Dinamarca", cx: 385, cy: 185, neighbors: ["sweden", "germany", "netherlands"] },
  netherlands: { name: "P. Bajos", cx: 345, cy: 220, neighbors: ["denmark", "germany", "belgium"] },
  belgium: { name: "Bélgica", cx: 330, cy: 250, neighbors: ["netherlands", "germany", "france", "luxembourg"] },
  luxembourg: { name: "Luxemburgo", cx: 355, cy: 270, neighbors: ["belgium", "germany", "france"] },
  germany: { name: "Alemania", cx: 395, cy: 240, neighbors: ["denmark", "netherlands", "belgium", "luxembourg", "france", "switzerland", "austria", "czech", "poland"] },
  poland: { name: "Polonia", cx: 455, cy: 220, neighbors: ["germany", "czech", "slovakia", "ukraine", "belarus", "russia_nw", "lithuania"] },
  belarus: { name: "Bielorrusia", cx: 510, cy: 205, neighbors: ["poland", "russia_nw", "ukraine", "lithuania", "latvia"] },
  lithuania: { name: "Lituania", cx: 480, cy: 185, neighbors: ["poland", "belarus", "latvia", "kaliningrad"] },
  latvia: { name: "Letonia", cx: 500, cy: 165, neighbors: ["lithuania", "estonia", "belarus"] },
  estonia: { name: "Estonia", cx: 510, cy: 145, neighbors: ["latvia", "russia_nw"] },
  kaliningrad: { name: "Kaliningrado", cx: 455, cy: 185, neighbors: ["poland", "lithuania"] },
  france: { name: "Francia", cx: 315, cy: 295, neighbors: ["great_britain", "belgium", "luxembourg", "germany", "switzerland", "italy", "spain"] },
  switzerland: { name: "Suiza", cx: 360, cy: 295, neighbors: ["france", "germany", "austria", "italy"] },
  austria: { name: "Austria", cx: 410, cy: 290, neighbors: ["germany", "switzerland", "italy", "czech", "slovakia", "hungary", "slovenia"] },
  czech: { name: "Chequia", cx: 420, cy: 255, neighbors: ["germany", "poland", "slovakia", "austria"] },
  slovakia: { name: "Eslovaquia", cx: 450, cy: 270, neighbors: ["czech", "poland", "ukraine", "hungary", "austria"] },
  ukraine: { name: "Ucrania", cx: 530, cy: 255, neighbors: ["poland", "slovakia", "hungary", "romania", "moldova", "russia_nw", "belarus"] },
  moldova: { name: "Moldavia", cx: 535, cy: 290, neighbors: ["ukraine", "romania"] },
  hungary: { name: "Hungría", cx: 450, cy: 295, neighbors: ["austria", "slovakia", "ukraine", "romania", "serbia", "croatia", "slovenia"] },
  slovenia: { name: "Eslovenia", cx: 415, cy: 310, neighbors: ["austria", "hungary", "croatia", "italy"] },
  croatia: { name: "Croacia", cx: 425, cy: 325, neighbors: ["hungary", "slovenia", "serbia", "bih"] },
  bih: { name: "Bosnia", cx: 435, cy: 345, neighbors: ["croatia", "serbia", "montenegro"] },
  serbia: { name: "Serbia", cx: 455, cy: 335, neighbors: ["hungary", "croatia", "bih", "montenegro", "romania", "bulgaria", "north_macedonia", "kosovo"] },
  kosovo: { name: "Kosovo", cx: 465, cy: 355, neighbors: ["serbia", "north_macedonia", "albania", "montenegro"] },
  montenegro: { name: "Montenegro", cx: 445, cy: 360, neighbors: ["croatia", "bih", "serbia", "kosovo", "albania"] },
  albania: { name: "Albania", cx: 455, cy: 380, neighbors: ["montenegro", "kosovo", "north_macedonia", "greece"] },
  north_macedonia: { name: "N. Macedonia", cx: 470, cy: 375, neighbors: ["serbia", "kosovo", "albania", "bulgaria", "greece"] },
  romania: { name: "Rumanía", cx: 495, cy: 305, neighbors: ["ukraine", "moldova", "hungary", "serbia", "bulgaria"] },
  bulgaria: { name: "Bulgaria", cx: 490, cy: 360, neighbors: ["romania", "serbia", "north_macedonia", "greece", "turkey_eu"] },
  greece: { name: "Grecia", cx: 475, cy: 410, neighbors: ["albania", "north_macedonia", "bulgaria", "turkey_eu"] },
  turkey_eu: { name: "Turquía (EU)", cx: 530, cy: 395, neighbors: ["bulgaria", "greece"] },
  italy: { name: "Italia", cx: 390, cy: 345, neighbors: ["france", "switzerland", "austria", "slovenia"] },
  spain: { name: "España", cx: 265, cy: 355, neighbors: ["france", "portugal"] },
  portugal: { name: "Portugal", cx: 230, cy: 360, neighbors: ["spain"] },
};